#!/bin/bash

wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores 'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=1&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores 'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=2&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=3&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=4&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=5&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=6&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=7&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=8&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=9&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=10&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=11&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&
wget -r --level=1000000 --tries=100 --retry-connrefused --include-directories=athlete,scores  'http://games.crossfit.com/scores/leaderboard.php?stage=3&sort=0&division=12&region=0&numberperpage=60&page=0&competition=0&frontpage=0&expanded=0&full=1&year=13&showtoggles=0&hidedropdowns=0&showathleteac=1&athletename='&

